name: VerityOps Build & Verify
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install deps & clone avbtool
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y e2fsprogs xxd openssl git python3 gzip
          git clone https://android.googlesource.com/platform/external/avb
          test -f avb/avbtool.py || { echo "avbtool.py missing"; exit 1; }

      - name: Generate demo AVB key
        run: |
          openssl genrsa -out testkey_rsa2048.pem 2048
          openssl rsa -in testkey_rsa2048.pem -pubout -out testkey_rsa2048_pub.pem

      - name: Create ext4 image (16MiB)
        run: bash scripts/make_ext4.sh system.img 16

      - name: Add dm-verity hashtree
        run: bash scripts/add_hashtree.sh system.img system_with_hashtree.img testkey_rsa2048.pem 8

      - name: Make vbmeta
        run: bash scripts/make_vbmeta.sh system_with_hashtree.img testkey_rsa2048.pem vbmeta.img

      - name: Inspect descriptors
        run: bash scripts/inspect.sh system_with_hashtree.img vbmeta.img .

      - name: Compress & hash artifacts
        run: |
          gzip -9c system_with_hashtree.img > system_with_hashtree.img.gz
          gzip -9c vbmeta.img > vbmeta.img.gz
          sha256sum system_with_hashtree.img.gz vbmeta.img.gz info_image.txt info_vbmeta.txt > checksums.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verity-artifacts
          path: |
            system_with_hashtree.img.gz
            vbmeta.img.gz
            info_image.txt
            info_vbmeta.txt
            checksums.sha256
            testkey_rsa2048.pem
            testkey_rsa2048_pub.pem

  verify:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - uses: actions/download-artifact@v4
        with: { name: verity-artifacts }

      - name: Decompress
        run: |
          gunzip -c system_with_hashtree.img.gz > system_with_hashtree.img
          gunzip -c vbmeta.img.gz > vbmeta.img

      - name: Clone avbtool
        run: |
          git clone https://android.googlesource.com/platform/external/avb
          test -f avb/avbtool.py || { echo "avbtool.py missing"; exit 1; }

      - name: Verify dm-verity presence
        run: |
          python3 avb/avbtool.py info_image --image vbmeta.img | tee verify_vbmeta.txt
          python3 avb/avbtool.py info_image --image system_with_hashtree.img | tee verify_image.txt
          egrep -i "hashtree|hash tree|dm-verity" verify_vbmeta.txt verify_image.txt >/dev/null \
            || (echo "No hashtree/dm-verity descriptors found" && exit 1)

      - name: Publish summary
        run: |
          {
            echo "## VerityOps — Run Summary"
            echo ""
            echo "### vbmeta descriptors"
            echo '```'
            python3 avb/avbtool.py info_image --image vbmeta.img
            echo '```'
            echo ""
            echo "### system_with_hashtree descriptors"
            echo '```'
            python3 avb/avbtool.py info_image --image system_with_hashtree.img
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
