name: VerityOps Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true   # pull the real 4.1 GB system.img, not the LFS pointer

      - name: Clone avbtool
        run: |
          git clone https://android.googlesource.com/platform/external/avb
          ls -la avb   # sanity check: should show avbtool.py at repo root

      - name: Generate Verity Metadata (vbmeta.img)
        run: |
          # Try to build vbmeta from descriptors inside system.img.
          # Not all emulator images have footers/hashtrees in system.img; if not, this will no-op gracefully.
          python3 avb/avbtool.py make_vbmeta_image \
            --include_descriptors_from_image system.img \
            --output vbmeta.img || echo "Skipping vbmeta generation (no descriptors/footer found in system.img)"

      - name: Upload vbmeta (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta
          path: vbmeta.img
          if-no-files-found: ignore

  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true   # again: fetch the real system.img

      - name: Clone avbtool
        run: |
          git clone https://android.googlesource.com/platform/external/avb
          ls -la avb   # should show avbtool.py

      - name: Verify dm-verity / hashtree presence
        run: |
          # avbtool info_image prints descriptors; on images with hashtree (dm-verity) you'll see "Hashtree" fields.
          # Grep for several canonical tokens to avoid brittle matching.
          python3 avb/avbtool.py info_image --image system.img | tee info.txt
          egrep -i "hashtree|hash tree|dm-verity" info.txt >/dev/null \
            || (echo "❌ No hashtree/dm-verity descriptors found in system.img" && exit 1)

      - name: Upload info dump (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: info-image
          path: info.txt
