name: VerityOps Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install avbtool
        run: |
          sudo apt update
          sudo apt install -y git python3
          git clone https://android.googlesource.com/platform/external/avb
          echo "alias avbtool='python3 $(pwd)/avb/avbtool'" >> ~/.bashrc
          source ~/.bashrc
          
      - name: Generate Verity Metadata
        run: |
          avbtool make_vbmeta_image \
            --include_descriptors_from_image system.img \
            --output vbmeta.img || echo "Skipping metadata since dummy image"

  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Clone avbtool
        run: |
          git clone https://android.googlesource.com/platform/external/avb

      - name: Verify dm-verity metadata
        run: |
          python3 avb/avbtool info_image --image system.img | grep "dm-verity" || (echo "dm-verity not found in system.img" && exit 1)


